### ISSUE TITLE
Yarn Install Fails

### ISSUE THREAD

**Issue by pooleja** [horizon-games/remix-app#2]
$ yarn install
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ node scripts/remix-dl.js
Unable to download remix file, status: 404
Unhandled rejection Error: invalid signature: 0x4f44213c

On Mac.

**Comment by caa1982** [comment]
same on Linux

**Comment by pkieltyka** [comment]
fixed in 67e5a08cfd43cf8df2fafe9f40b0b11c7b865883
